export const ADD_SERVICE = 'ADD_SERVICE';
export const UPDATE_SERVICE = 'UPDATE_SERVICE';
export const DELETE_SERVICE = 'DELETE_SERVICE';

export const SET_FORM_FIELD = 'SET_FORM_FIELD';
export const START_EDITING = 'START_EDITING';
export const CANCEL_EDITING = 'CANCEL_EDITING';
export const CLEAR_FORM = 'CLEAR_FORM';
export const SET_VALIDATION_ERRORS = 'SET_VALIDATION_ERRORS';